### ISSUE TITLE
List of core data packages with statuses in status.csv 

### ISSUE THREAD

**Issue by Mikanebu** [datahq/core-datasets-tools#1]
We want to have our list of all core data packages in status.csv with necessary columns. 

## Acceptance criteria

* [x] created status.csv using `https://raw.githubusercontent.com/datasets/registry/master/core-list.txt`(sorted alphabetically)
* [x] lower case headings

## Tasks

* [x] Create status.csv  using https://raw.githubusercontent.com/datasets/registry/master/core-list.txt

**Comment by Mikanebu** [comment]
FIXED
