### ISSUE TITLE
Add norm function

### ISSUE THREAD

**Issue by Mikanebu** [datahq/core-datasets-tools#17]
We want to have a function to normalize core data packages

## Acceptance criteria

* [x] I have `index.js norm` command to normalize data packages

## Tasks

* [x] create function to normalize data packages
* [x] run check and push

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/core-datasets-tools/commit/2f843b7cff8edcd2a2fb5bcb0056c6cc9565537c
