### ISSUE TITLE
Misc improvements

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/core-datasets-tools#19]
At the moment, if I do push several times it push everything again and again. But I want to be able to push packages, then fix those ones that was not pushed and then push again only those packages.

## Acceptance criteria

* [x] when I do push I want to push only those packages that are not pushed yet (published status is false)
* [x] when I do check and a package's status changes it should make `published` status `false`, so we know that this package should be re-published (so it gets pushed when I do push)
* [x] validate messages should say `valid` instead of empty string

## Tasks

* [x] refactor `push` function to push only those that are not pushed yet.
* [x] refactor `check` function 
  * [x] to update column `published` if `validation` is false 
  * [x] to change message in `validation_messages` columns to `valid`

**Comment by Mikanebu** [comment]
@anuveyatsu I want to clarify about 2nd criteria in 'Acceptance criteria`.  Package's status changes means `validated_metadata` and `validated_data` columns?

**Comment by anuveyatsu** [comment]
@Mikanebu I mean if `validated` status (either for metadata or data) was changed it also should set `published` to false.

**Comment by anuveyatsu** [comment]
FIXED in #20
