### ISSUE TITLE
Set up the following scripts

### ISSUE THREAD

**Issue by Mikanebu** [datahq/core-datasets-tools#2]
We want to have scripts to clone, check and push core data packages.

## Acceptance criteria

* [x] sciprt to run all the modules in index.js
* [x] script to do clone in `index.js`(don't clone if there... then do git pull
* [x] script to do check in `index.js`(plus normalize part as well)
* [x] script to to do push in `index.js`

## Tasks
* [x] Created function to check and fix(validate and normalize)
* [x] Create function to clone core data packages(if exists, git pull)
* [x] Create function to push core data packages
* [x] create script index.js to run all the abovementionaed commands

**Comment by Mikanebu** [comment]
FIXED
