### ISSUE TITLE
we need a user for the example data packages

### ISSUE THREAD

**Issue by Mikanebu** [datahq/core-datasets-tools#22]
We want a new user to publish `example` data packages.

## Acceptance criteria

* [x] `example` data packages are published under `examples` user
 
## Tasks

* [x] create a user in DP with `username`: `examples`
* [x] get token from `auth`
* [x] create `example.csv` for `example` data packages

**Comment by Mikanebu** [comment]
FIXED
