### ISSUE TITLE
refactor index.js to use new datahub-cli lib without babel

### ISSUE THREAD

**Issue by Mikanebu** [datahq/core-datasets-tools#25]
We want to have index.js refactored, so it will not use packages from `/dist` anymore.

## Acceptance criteria

* [ ] Refactored index.js

## Tasks

* [ ] Refactor index.js 
* [ ] Refactor tests if required

**Comment by Mikanebu** [comment]
FIXED
