### ISSUE TITLE
Analyse wrangling of core datasets to inform automation

### ISSUE THREAD

**Issue by Mikanebu** [datahq/core-datasets-tools#28]
We want to have a spreadsheet with the following columns such as modified, last modified, source data format, number of resources, script, language, complexity, notes in order to get full information about our core datasets. 

## Acceptance criteria

* [x] all 59 core datasets analysed with columns filled out in spreadsheet

## Tasks

* [x] Create sheet with new headings and check these with @akariv 
* [x] Do 2-5 sample datasets analysis to inform how easy this is and whether worth doing
* [x] Do for all of them
* [x] Write up learnings - how complex are these scripts, are there common features, what is the usual language etc

## Analysis

Since we have already had a [spreadsheet](https://docs.google.com/spreadsheets/d/14kJluhePaMOx6vYBic0poVjDYK3I8-v_xF3sv4Focac/edit#gid=405792816) about core datasets, we can create new sheet `core datasets analysis`. 
Columns will be: `name, github_url, datahub_url, modified, last modified, source data format, number of resources, script, language, complexity, notes`

| columns  | description  |
|---|---|
| name  | name of the dp  |
| github_url | GitHub url  |
| datahub_url | datahub.io published url  |
| modified | no, daily, weekly, monthly, quarterly, annually  |
| last_modified  | original source updated time  |
| source data format  | for example `csv, json etc`  |
| number of resources |  quantity of the resource in metadata  |
| script | can accept only `YES` or `NO`  |
| language | the language of the written script to get data. For example: `java, shell, python and so on`  |
| cleaning steps are needed  | or example: `remove header rows, clean values, remove footnotes, normalise formats etc`  |
| complexity  |  the level of difficulty. 1 - simple, 2 - normal, 3 - complex  |

### Learnings: 

According to the core datasets analysis on [spreadsheet](https://docs.google.com/spreadsheets/d/14kJluhePaMOx6vYBic0poVjDYK3I8-v_xF3sv4Focac/edit#gid=405792816), we can say the following:
* There are 44 core datasets with written script out of 59
  * Python = 27
  * Shell = 6
  * Shell with tuttle = 4 
    * Used for `geojson` format
* Depending on the size and operations done on the scripts, I divided them into 3 categories: 
  * 1 - easy: 11 scripts
    * Read csv - remove_headers - write csv 
    * Read txt - write to csv
  * 2 - normal: 13 scripts
    * normalise date format
  * 3 - complex 17 scripts
    * using more than one language
    * `geojson` format
    * scraping `html-table`
* The most popular source data formats:
  * csv - 17
  * xls - 9
  * txt - 6 
* In total 33 core data packages modified contantly
  * annually - 14
  * quarterly - 2
  * monthly - 9
  * weekly - 1
  * daily - 6
  * not able to find - 1

**Comment by Mikanebu** [comment]
FIXED, analysis core datasets is located in [google spreadsheet](https://docs.google.com/spreadsheets/d/14kJluhePaMOx6vYBic0poVjDYK3I8-v_xF3sv4Focac/edit#gid=405792816)  and in the summary section above
