### ISSUE TITLE
Setup linter

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/core-datasets-tools#8]
Use approach from our cli lib - https://github.com/datahq/datahub-cli

See `package.json` for `xo` configs:
```
"xo": {
    "space": true,
    "semicolon": false,
    "rules": {
      "no-var": "warn",
      "no-use-before-define": 1,
      "no-await-in-loop": 1,
      "import/prefer-default-export": 1,
      "no-negated-condition": 1,
      "guard-for-in": 1
    },
    "ignores": [
      "test/fixtures/*/**"
    ]
  }
```

Also for `scripts`:
```
"scripts": {
  ...,
  "lint": "xo --quiet",
  ...
}
```

## Acceptance criteria

* [x] I can run `npm run lint` to validate everything is written according JS standards

## Tasks

* [x] install `xo` as dev dependancy
* [x] setup configs in `package.json`
* [x] run and fix all errors (notice, you can use smth like `xo --fix` to auto-fix some errors)
* [x] update readme (add sections for lint and test)

**Comment by Mikanebu** [comment]
FIXED
